Repository FinishLine-CKU/FinishLine_FE, pull requests merged in 2025-02, with the labels that each got.

#34 FE 기이수 과목 등록 페이지 기능 구현
  src/components/doneLectureComponents.jsx
  src/components/uploadPdfComponents.jsx
  src/pages/doneLecturePage.jsx
  src/pages/signupPage2.jsx
Labels: enhancement

#35 #20 마이페이지 회원정보 수정 및 모달 개발 : modal, featureModal
  src/App.js
  src/assets/images/loading.gif
  src/components/featureModal.jsx
  src/components/header.jsx
  src/components/modal.jsx
  src/components/sideBar.jsx
  src/pages/loginPage.jsx
  src/pages/myPage.jsx
  src/pages/signupPage1.jsx
  src/pages/signupPage2.jsx
  src/pages/userGuidePage.jsx
  src/utils/hooks/modalContext.jsx
Labels: enhancement

#37 Refactoring
  package.json
  src/App.js
  src/assets/images/graduatedstudent.png
  src/assets/images/notgood.png
  src/assets/images/sogood.png
  src/components/doneLectureComponents.jsx
  src/components/graduChartComponents.jsx
  src/components/header.jsx
  src/components/uploadPdfComponents.jsx
  src/pages/doneLecturePage.jsx
  src/pages/graduTestPage.jsx
  src/pages/myPage.jsx
  src/pages/signupPage1.jsx
  src/pages/uploadPdfPage.jsx
  src/pages/userGuidePage.jsx
  yarn.lock
Labels: enhancement

#38 Graduationcheck
  FETCH_HEAD
  src/components/doneLectureComponents.jsx
  src/components/footer.jsx
  src/components/graduChartComponents.jsx
  src/components/uploadPdfComponents.jsx
  src/pages/doneLecturePage.jsx
  src/pages/graduTestPage.jsx
  src/pages/loginPage.jsx
  src/pages/myPage.jsx
Labels: enhancement

#41 Refactoring 회원가입 무한 로딩, 회원정보 로직 한글 > 코드, localStorage 활용 범위
  src/components/uploadPdfComponents.jsx
  src/pages/graduTestPage.jsx
  src/pages/loginPage.jsx
  src/pages/myPage.jsx
  src/pages/signupPage1.jsx
Labels: bug

#42 로딩 화면 스타일 개선
  package.json
  src/assets/images/AnimationCKU.json
  src/components/loadingComponents.jsx
  src/components/uploadPdfComponents.jsx
  src/pages/graduTestPage.jsx
  src/pages/myPage.jsx
  yarn.lock
Labels: enhancement

#43 피드백 폼 링크 확장 작업
  src/assets/images/chillGuy.png
  src/components/footer.jsx
  src/pages/graduTestPage.jsx
  src/pages/signupPage1.jsx
Labels: documentation, enhancement
